config/routes.rb
Rails.application.routes.draw do

  root to: 'index#home'
  get '/contact' => 'index#contact'
  resources :students, :courses, :classrooms

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  before_create do
   self.entry_at = Time.now
 end
end

app/models/course.rb
class Course < ActiveRecord::Base
  extend EnumerateIt
  has_enumeration_for :status, with: CourseStatus

  validates :name,  presence: true, length: { maximum: 45 }
  validates :description, presence: true, length:  { maximum: 45 }
end

app/models/course_status.rb
class CourseStatus < EnumerateIt::Base
  associate_values(
    active:   [1, 'Ativo'],
    inactive:  [2, 'Inativo']
  )
end

app/models/student.rb
class Student < ActiveRecord::Base
  extend EnumerateIt
  has_enumeration_for :status, with: StudentStatus

  validates :name,  presence: true, length: { maximum: 45 }
  validates :register_number, presence: true, length:  { maximum: 45 }, uniqueness: { case_sensitive: false }
end

app/models/student_status.rb
class StudentStatus < EnumerateIt::Base
  associate_values(
    active:   [1, 'Ativo'],
    inactive:  [2, 'Inativo']
  )
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def new
    @students = Student.all
    @courses = Course.all
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      redirect_to classrooms_path
    else
      render :new
    end
  end

  def index
    @classroom = Classroom.all
  end

  def destroy
    @classroom = Classroom.find(params[:id]).destroy
    redirect_to classrooms_path
  end

  def edit
    @students = Student.all
    @courses = Course.all
    @classroom = Classroom.find(params[:id])
  end

  def update
    @classroom = Classroom.find(params[:id])
    if @classroom.update(classroom_params)
      redirect_to classrooms_path
    else
      render :new
    end
  end


  private

  def classroom_params
    params.require(:classroom).permit(:student_id, :course_id)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy
    @courses = Course.find(params[:id]).destroy
    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :status)
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  responders :flash
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      respond_with @student, location: -> { students_path }
    else
      render :new
    end
  end

  def destroy
    @student = Student.find(params[:id]).destroy
    redirect_to students_path
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      respond_with @student, location: -> { students_path }
    else
      render :edit
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  private

  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Classmate"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/_form.html.slim
div class="Container"
  div class="row"
    div class="col-md-6 col-md-offset-3"
      = form_for(@classroom) do |f|

        = f.label :student_id
        = f.select :student_id, options_from_collection_for_select(@students, "id", "name"), class: 'form-control'

        = f.label :course_id
        = f.select :course_id, options_from_collection_for_select(@courses, "id", "name"), class: 'form-control'

        = f.submit "Confirmar", class: "btn btn-primary"

app/views/classrooms/edit.html.slim
= render 'form'

div class='button'
  = link_to "Voltar", classrooms_path

app/views/classrooms/index.html.slim
div class="container"
  = link_to "Criar nova Matrícula", new_classroom_path, class: "btn btn-lg btn-primary"
  p
  div class="row"
    div class="rol-md-6"
      table class="table"
        thead
          tr
            th name
            th curso
            th data de matrícula
        tbody
        - @classroom.each do |s|
          tr
            td = s.student.name
            td = s.course.name
            td = I18n.l(s.entry_at, format: :short)
            td = link_to "Editar", edit_classroom_path(s)
            td = link_to "Excluir", s, method: :delete

  div class='button'
    = link_to "Voltar", root_path

app/views/classrooms/new.html.slim
div class="Container"
  div class="row"
    div class="col-md-6 col-md-offset-3"
      = form_for(@classroom) do |f|

        = f.label :student_id
        = f.select :student_id, options_from_collection_for_select(@students, "id", "name"), class: 'form-control'

        = f.label :course_id
        = f.select :course_id, options_from_collection_for_select(@courses, "id", "name"), class: 'form-control'

        = f.submit "Confirmar", class: "btn btn-primary"

app/views/courses/_form.html.slim
div class="Container"
  div class="row"
    div class="col-md-6 col-md-offset-3"
      = form_for(@course) do |f|
        = f.label :name
        = f.text_field :name, class: 'form-control'

        = f.label :description
        = f.text_field :description, class: 'form-control'

        = f.label :status
        = f.select :status, CourseStatus.to_a, class: 'form-control'

        = f.submit "Confirmar", class: "btn btn-primary"

app/views/courses/edit.html.slim
= render 'form'

div class='button'
  = link_to "Voltar", courses_path

app/views/courses/index.html.slim
div class="container"
  = link_to "Criar novo Curso", new_course_path, class: "btn btn-lg btn-primary"
  p
  div class="row"
    div class="rol-md-6"
      table class="table"
        thead
          tr
            th name
            th description
            th status
        tbody
        - @courses.each do |s|
          tr
            td = s.name
            td = s.description
            td = s.status_humanize
            td = link_to "Editar", edit_course_path(s)
            td = link_to "Excluir", s, method: :delete

  div class='button'
    = link_to "Voltar", root_path

app/views/courses/new.html.slim
= render 'form'

div class='button'
  = link_to "Voltar", courses_path

app/views/index/contact.html.slim
h2 hliviero@gmail.com

app/views/index/home.html.slim
div class="center jumbotron"
  h1 Bem Vindo ao Classmate
  = link_to "New Registration", new_classroom_path, class: "btn btn-lg btn-primary"

app/views/layouts/_footer.html.slim
footer class="footer"
  nav
   ul
    li = link_to "Contact", contact_path

app/views/layouts/_header.html.slim
header class="navbar navbar-fixed-top navbar-inverse"
  div class="container"
    = link_to "Classmate", root_path, id: "logo"
    nav
    ul class="nav navbar-nav navbar-right"
      li = link_to "Home", root_path
      li = link_to "Students", students_path
      li = link_to "Courses", courses_path
      li = link_to "Registration", classrooms_path

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/students/_form.html.slim
div class="Container"
  div class="row"
    div class="col-md-6 col-md-offset-3"
      = form_for(@student) do |f|
        = f.label :name
        = f.text_field :name, class: 'form-control'

        = f.label :register_number
        = f.text_field :register_number, class: 'form-control'

        = f.label :status
        = f.select :status, StudentStatus.to_a, class: 'form-control'

        = f.submit "Confirmar", class: "btn btn-primary"

app/views/students/edit.html.slim
= render 'form'

div class='button'
  = link_to "Voltar", students_path

app/views/students/index.html.slim
div class="container"
  = link_to "Criar novo Estudante", new_student_path, class: "btn btn-lg btn-primary"
  p
  div class="row"
    div class="rol-md-6"
      table class="table"
        thead
          tr
            th name
            th register_number
            th status
        tbody
        - @students.each do |s|
          tr
            td = s.name
            td = s.register_number
            td = s.status_humanize
            td = link_to "Editar", edit_student_path(s)
            td = link_to "Excluir", s, method: :delete

  div class='button'
    = link_to "Voltar", root_path

app/views/students/new.html.slim
= render 'form'

div class='button'
  = link_to "Voltar", students_path